# Generated by Django 2.2 on 2023-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biaosheng',
            fields=[
                ('bi', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gedan',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=32)),
                ('nr', models.CharField(max_length=32)),
                ('bfl', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=32)),
                ('pname', models.CharField(max_length=32)),
                ('tname', models.CharField(max_length=32)),
                ('imgsrc', models.CharField(max_length=64)),
                ('mp3', models.CharField(max_length=64)),
                ('txt', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gename', models.CharField(max_length=16, verbose_name='名字')),
                ('singname', models.CharField(max_length=16, verbose_name='名字')),
                ('zhuanname', models.CharField(max_length=16, verbose_name='名字')),
            ],
        ),
        migrations.CreateModel(
            name='Rege',
            fields=[
                ('ri', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('userpwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Xindie',
            fields=[
                ('xd', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=32)),
                ('mname', models.CharField(max_length=32)),
                ('zuozhe', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Xinge',
            fields=[
                ('xi', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=32)),
            ],
        ),
    ]
